@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
!pragma useVerticalIf on
start
:User executes add command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.



 partition AddCommandParser{
    if () then ([else])
        :ParseException: Invalid module code format;
           stop

    ( [valid module code format]) elseif () then ( [else])
        :ParseException: Invalid command format;
        stop
    else ( [valid command format])

    endif
    }

partition Addcommand {

if () then ([else])
    :ModuleNotFoundException: Module Not Found;
    stop
( [Module is in ModuleData]) elseif() then([else])
    :DuplicateModuleException: Module already Added;
    stop
    
else ( [Module not in ModulePlan] )
endif
}

:Add Command runs successfully
Module is added to module plan;
stop



@enduml
