@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

ModulePlan *-right-> "1" UniqueModuleList
ModulePlan *-right-> "1" UniqueTagList
UniqueTagList -[hidden]down- UniqueModuleList
UniqueTagList -[hidden]down- UniqueModuleList

UniqueTagList -right-> "*" Tag
UniqueModuleList -right-> Module

Module -up-> "*" Tag

Module *--> ModuleCode
Module *--> Grade
Module *--> Lecturer
Module *--> ModuleCredit
Module *--> Semester
Module *--> Year
Module *--> ModuleName
@enduml
