@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModulePlanParser" as ModulePlanParser LOGIC_COLOR
participant ":DeleteCommandParser" as DeleteCommandParser LOGIC_COLOR
participant "d:DeleteCommand" as DeleteCommand LOGIC_COLOR
participant "result:CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant "m:Module" as Module MODEL_COLOR
participant "model:Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute("delete CS3230")
activate LogicManager

LogicManager -> ModulePlanParser : parseCommand("delete CS3230")
activate ModulePlanParser

create DeleteCommandParser
ModulePlanParser -> DeleteCommandParser
activate DeleteCommandParser

DeleteCommandParser --> ModulePlanParser
deactivate DeleteCommandParser

ModulePlanParser -> DeleteCommandParser : parse(arg)
activate DeleteCommandParser

create DeleteCommand
DeleteCommandParser -> DeleteCommand : new DeleteCommand("CS3230")
activate DeleteCommand

DeleteCommand --> DeleteCommandParser
deactivate DeleteCommand

DeleteCommandParser --> ModulePlanParser : d
deactivate DeleteCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
DeleteCommandParser -[hidden]-> ModulePlanParser
destroy DeleteCommandParser

ModulePlanParser --> LogicManager : d
deactivate ModulePlanParser

LogicManager -> DeleteCommand : execute(model)
activate DeleteCommand

DeleteCommand -> Model : checkDbValidModuleCode("CS3230")
activate Model

Model --> DeleteCommand
deactivate Model

DeleteCommand -> Model : getModule("CS3230")
activate Model

Model --> DeleteCommand : targetMod
deactivate Model

DeleteCommand -> Model : deleteModule(targetMod)
activate Model

Model --> DeleteCommand
deactivate Model

create CommandResult
DeleteCommand -> CommandResult
activate CommandResult

CommandResult --> DeleteCommand
deactivate CommandResult

DeleteCommand --> LogicManager : result
deactivate DeleteCommand
DeleteCommand -[hidden]-> LogicManager : result
destroy DeleteCommand

[<--LogicManager : result
deactivate LogicManager
@enduml
