@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "Model                 " as ModelPackage <<Rectangle>>{
Class "<<interface>>\nModel" as Model
Class ModelManager

Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class ReadOnlyUserPrefs
Class UserPrefs

Class "<<interface>>\nReadOnlyModulePan" as ReadOnlyModulePlan
Class ReadOnlyModulePlan
Class ModulePlan
Class ModulePlanSemesterList
Class ModulePlanSemester
Class UniqueModuleList
Class Module

Class Description
Class ModularCredit
Class Grade
Class ModuleCode
Class ModuleName
Class Year
Class Semester

Class "<<interface>>\nReadOnlyModuleData" as ReadOnlyModuleData
Class ModuleData
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModulePlan .up.|> ReadOnlyModulePlan

ModelManager .up.|> Model
Model ..> ReadOnlyUserPrefs
Model ..> ReadOnlyModulePlan
Model ..> ReadOnlyModuleData
ModelManager --> "1" ModulePlan
ModelManager --> "1" UserPrefs
ModelManager --> "1" ModuleData
ModelManager ..> Module
ModelManager ..> ModuleCode
ModuleData .up.|> ReadOnlyModuleData
UserPrefs .up.|> ReadOnlyUserPrefs

ModulePlan *--> "1" ModulePlanSemesterList
ModulePlanSemesterList --> "~*" ModulePlanSemester
ModulePlanSemester *-> "1" UniqueModuleList
ModuleData *--> "1" UniqueModuleList
UniqueModuleList -> "~*" Module

ModulePlanSemester --> "1" Year
ModulePlanSemester --> "1" Semester

Module *-> "1" ModuleCode
Module *--> "1" ModuleName
Module *--> "1" ModularCredit
Module --> "0..1" Grade
Module *--> "1" Description
Module --> "0..1" Year
Module --> "0..1" Semester

ReadOnlyModulePlan -[hidden]right--> ReadOnlyModuleData
ReadOnlyModuleData -[hidden]right--> ModelManager
ModelManager -[hidden]right--> ReadOnlyUserPrefs

Year -[hidden]right-> Semester
Semester -[hidden]right-> Grade


@enduml
