@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package "Model                 " as ModelPackage <<Rectangle>>{
Class "<<interface>>\nModel" as Model
Class ModelManager

Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class ReadOnlyUserPrefs
Class UserPrefs

Class "<<interface>>\nReadOnlyModulePan" as ReadOnlyModulePlan
Class ReadOnlyModulePlan
Class ModulePlan
Class ModulePlanSemesterList
Class ModulePlanSemester
Class UniqueModuleList
Class Module

Class "<<interface>>\nReadOnlyModuleData" as ReadOnlyModuleData
Class ModuleData
Class UniqueDbModuleList
Class DbModule
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ModulePlan .up.|> ReadOnlyModulePlan

ModelManager .up.|> Model
Model ..> ReadOnlyUserPrefs
Model ..> ReadOnlyModulePlan
Model ..> ReadOnlyModuleData
ModelManager --> "1" ModulePlan
ModelManager --> "1" UserPrefs
ModelManager --> "1" ModuleData
ModuleData .up.|> ReadOnlyModuleData
UserPrefs .up.|> ReadOnlyUserPrefs

ModulePlan *--> "1" ModulePlanSemesterList
ModulePlanSemesterList --> "~*" ModulePlanSemester
ModulePlanSemester --> "1" UniqueModuleList
ModuleData *--> "1" UniqueDbModuleList
UniqueDbModuleList --> "~* all" DbModule
UniqueModuleList -> "~*" Module

ReadOnlyModuleData -[hidden]right--> ModelManager
ModelManager -[hidden]right--> ReadOnlyModulePlan
ReadOnlyModulePlan -[hidden]right--> ReadOnlyUserPrefs
@enduml
