@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Class Module
Class DbModule
Class ModuleDescription
Class ModularCredit
Class Grade
Class ModuleCode
Class ModuleName
Class Year
Class Semester

Module --> "1" ModuleCode
Module --> "1" ModuleName
Module --> "1" ModularCredit
Module --> "1" Grade
Module --> "1" ModuleDescription
Module --> "1" Year
Module --> "1" Semester

DbModule -up-> "1" ModuleCode
DbModule -up-> "1" ModuleName
DbModule -up-> "1" ModularCredit
DbModule -up-> "1" ModuleDescription

ModuleCode -[hidden]right-> ModuleName
ModuleName -[hidden]right-> ModularCredit
ModularCredit -[hidden]right-> ModuleDescription
Grade -[hidden]right-> Semester
Semester -[hidden]right-> Year

@enduml
