@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "delete CS1010"

package States <<rectangle>> {
    class State1 as "<u>mp0:ModulePlan</u>"
    class State2 as "<u>mp1:ModulePlan</u>"
    class State3 as "<u>mp2:ModulePlan</u>"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3

class Pointer as "Current State" #FFFFFF

Pointer -up-> State2
@end
