@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":ModulePlanParser" as ModulePlanParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedModulePlan" as VersionedModulePlan MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> ModulePlanParser : parseCommand(undo)
activate ModulePlanParser

create UndoCommand
ModulePlanParser -> UndoCommand
activate UndoCommand

UndoCommand --> ModulePlanParser
deactivate UndoCommand

ModulePlanParser --> LogicManager : u
deactivate ModulePlanParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoModulePlan()
activate Model

Model -> VersionedModulePlan : undo()
activate VersionedModulePlan

VersionedModulePlan -> VersionedModulePlan :resetData(ReadOnlyModulePlan)
VersionedModulePlan --> Model :
deactivate VersionedModulePlan

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
